languageCode = "ja-jp"
title = "My New Hugo Site"
baseURL = "https://flashdesignfactory.github.io/flashdesignfactory.github.io"
canonifyurls = true

[params]
  description = "This is yourblog"
  author = "okd"

[taxonomies]
category = "categories"
tag = "tags"
